export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART:"ADD_TO_CART",
  DELETE_ITEM:"DELETE_ITEM",
  Remove_ONE:"REMOVE_ONE",
  LOGIN_REQUEST: 'LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  SIGNUP_REQUEST: 'SIGNUP',
  RESPONSE_ERROR: 'RESPONSE_ERROR',
  GET_ERRORS: 'GET_ERRORS',
  SUCCESS_MSSAGE: 'SUCCESS_MSSAGE'
};
